### ISSUE TITLE
可能存在的bug

### ISSUE THREAD

**Issue by SMUTTT** [YuLab-SMU/fanyi#10]
我申请的是百度翻译的通用翻译api
R version 是4.3.1
fanyi版本为GitHub版本
完全按照阅读文件中的示例

library(DOSE)
library(enrichplot)
data(geneList)
de <- names(geneList)[1:200]
x <- enrichDO(de)
p <- dotplot(x)
p2 <- translate_ggplot(p, axis='y')

p2中显示错误并重复八次
No valid result found.
Please check your network and credentials (appid and key)

p2图片中只有卵巢上皮癌症和胚胎瘤被翻译
其余全部为带括号的英文如(breast carcinoma)

运行en2cn('breast carcinoma')
translate('breast carcinoma')
可正确输出"乳腺癌"

有可能是存在bug吗？

**Comment by GuangchuangYu** [comment]
升级再试试。

**Comment by SMUTTT** [comment]
已解决 
good！
