### ISSUE TITLE
Discussion: Stage 1.

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [YuLab-SMU/fanyi#13]
Greetings,
    There are some R packages in CRAN that support translation APIs like Google Cloud and DeepL:
> Google's 'Natural Language' API, 'Cloud Translation' API, 'Cloud Speech' API and 'Cloud Text-to-Speech' API
[googleLanguageR](https://cran.r-project.org/web/packages/googleLanguageR/index.html)

> deeplr: Interface to the 'DeepL' Translation API
[deeplr](https://cran.r-project.org/web/packages/deeplr/index.html)

1) If we also support these translation platform, like even if we came up with a nicer implementation/broader function support of Google Cloud API, is there any possibility that we produce some fragmentations to the eco-system of R. (tl;dr: I think our goal should be made clear, what translation platform should we support, what do the potential users need.
[for me I think:
a. Supporting domestic translation platform is our top priority, since it is hard for domestic developers to find the documentation and develop package that supports these platform, even if the company made a great progress in the field of natural language processing]
b. It is also important to note that international translation platforms that are developed by conglomerate companies like Google/Microsoft who have decades of experience for inventing new algorithms like [transformer model](https://arxiv.org/abs/1706.03762) and train their neural networks upon large language dataset/linguistic corpus, and by applying feedback mechanism, or we should call this "supervised learning" method, achieved state-of-the-art performance in the translation field, therefore, they've handled a large proportion of translation queries worldwide, it's also important to have their translation API supported, too.
2) The former packages (googleLanguageR) existed for a few years I think, especially it was sponsored by [ropensci](https://ropensci.org/), I think after so many years, the developers of this package might have experiences to cope with problems like [error handling](https://github.com/ropensci/googleLanguageR/issues/55), so, it is necessary for us to add error message that comes from server side to help better diagnose the issue. 
3) Some packages mentioned that, if certain query exceeds the limit of the length, or, exceeds the limit of querying API (for domestic translation platform like Caiyun, it will only allow 10 QPS for the free subscription tier, that is 10 queries per second), which means if we vectorise the translation query, it is possible that we hit the upper limit of the API, thus error will be encountered. I guess we should also find solutions for this, too.

**Comment by GuangchuangYu** [comment]
1. Instead of having more translation services supported, I would like to connect the translation to other online information (e.g., gene information), see also <https://github.com/YuLab-SMU/ProjectYulab/issues/22>.
2. It is great to have abilities to handle errors.
3. We have a quick and dirty solution, see <https://github.com/YuLab-SMU/fanyi/blob/devel/R/translate.r#L188-L194>.

**Comment by GuangchuangYu** [comment]
@MitsuhaMiyamizu you are welcome to further contribute translation platform support if you like.

**Comment by MitsuhaMiyamizu** [comment]
Would you mind if I import [promise](https://rstudio.github.io/promises/) or [coro](https://github.com/r-lib/coro/) (which relies on the former package) to implement async/await operations?

**Comment by GuangchuangYu** [comment]
I don't mind :)

**Comment by GuangchuangYu** [comment]
for point 3, here is a possible solution:

![image](https://github.com/YuLab-SMU/fanyi/assets/626539/25bf00eb-94ef-4408-85d0-a5e6a2509577)
