### ISSUE TITLE
Feature Request: Invoke multiple translator simultaneously.

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [YuLab-SMU/fanyi#19]
One interesting idea struck to my mind just now, when we want to translate in a batch, we can actually set multiple translator backends, like 
```
translator_a <- set_translate_options(source = "a")
translator_b <- set_translate_options(source = "b")
...
translator_z <- set_translate_options(source = "z")
```
When we have a large amount of data needs to be translated, we just vectorize the translation task, randomly/[round-robin scheduling](https://en.wikipedia.org/wiki/Round-robin_scheduling)-ly distribute the tasks to the backend we've created. This might sound like the mechanism of [load balancing](https://en.wikipedia.org/wiki/Load_balancing_(computing)).

One more advantage this may have is that you have translation engine A that can translate from a to b very precisely,
and translation engine B have a better translation performance from b to c, then you can chain them up, say:
```
input %>% translator_a(from = "a", to = "b") %>% translator_b(from = "b", to = "c")
```
And it may perform even better than either
```
input %>% translator_a(from = "a", to = "c")
```
or
```
input %>% translator_b(from = "a", to = "c")
```

**Comment by GuangchuangYu** [comment]
![image](https://github.com/YuLab-SMU/fanyi/assets/626539/049aa008-1931-44fc-bf03-59314686f8f2)


IMO, it is supported.

**Comment by GuangchuangYu** [comment]
![image](https://github.com/YuLab-SMU/fanyi/assets/626539/252daa13-60d1-44c0-b8e0-e373621a4e1d)


the output from chatglm is almost Chinese, and I use baidu to translate it. The output is quite different. 

Did I make a mistake in using chatglm?

**Comment by MitsuhaMiyamizu** [comment]
based on the research literature published by their team, chatglm only supports English and Chinese, it's bilingual, at least for now.
