### ISSUE TITLE
translate_ggplot函数报错

### ISSUE THREAD

**Issue by ydx1013** [YuLab-SMU/fanyi#20]
Error in names(tlab) <- lab : 
  'names'属性的长度[20]必需和矢量的长度[0]一样
>       p2 = fanyi::translate_ggplot(p1, axis = "y", from = "en", to = "zh")
>       print(p2)

**Comment by ydx1013** [comment]
选择翻译X轴的时候，报错，不填写x轴的时候，运行正常，但是写成循环运行就报错了。不知道为什么。fanyi::translate_ggplot(p1, axis = "xy", from = "en", to = "zh")
Error in names(tlab) <- lab : 
  'names'属性的长度[20]必需和矢量的长度[0]一样

**Comment by GuangchuangYu** [comment]
得有可重复的例子。

**Comment by ydx1013** [comment]
正在看translate_ggplot函数，找到错误后和您说。

**Comment by ydx1013** [comment]
使用的百度翻译，找到原因了，请求太快，输出为空，导致'names'属性的长度[20]必需和矢量的长度[0]一样，为空，可以适当添加延时Sys.sleep(sample(1:5, 1))，大模型估计更容易返回值为空。余老师，pdf中的中文，在pdf文件中显示为  ....         Rstudio控制台输出是正常的。如何解决这个问题呢？

**Comment by yeqwe** [comment]
已解决。

**Comment by ydx1013** [comment]
使用的百度翻译，找到原因了，请求太快，输出为空，导致'names'属性的长度[20]必需和矢量的长度[0]一样，为空，可以适当添加延时Sys.sleep(sample(1:5, 1))，大模型估计更容易返回值为空。

**Comment by PengGongxin** [comment]
I meet a bug:
"translate_ggplot(plot, axis='y')
Error in while (nchar(st) > width) { : 
  missing value where TRUE/FALSE needed"
what should  I do? Thanks

**Comment by yisheng1997** [comment]
我也遇到了这个问题，后来把百度翻译换成了有道翻译就解决了

> 使用的百度翻译，找到原因了，请求太快，输出为空，导致'names'属性的长度[20]必需和矢量的长度[0]一样，为空，可以适当添加延时Sys.sleep(sample(1:5, 1))，大模型估计更容易返回值为空。

我也遇到了这个问题，我是把百度翻译换成了有道翻译，就解决了
