### ISSUE TITLE
翻译返回空，没有报错

### ISSUE THREAD

**Issue by amingson** [YuLab-SMU/fanyi#21]
Y叔您好，看到您发布的这个新的工具，迫不及待的就想要来用用看。
成功的安装过后，按照示例代码运行后返回empty，但没有任何报错，如下所示。
![image](https://github.com/YuLab-SMU/fanyi/assets/102129816/02c0db42-ecdd-48e8-b191-3ea28e5a21fa)

请问您是否有什么好的建议？
期待您的回复！！！

祝好
Msong

**Comment by GuangchuangYu** [comment]
![image](https://github.com/YuLab-SMU/fanyi/assets/626539/d2ed118b-6cea-46ec-8442-24315e970fdd)

是否有开通翻译服务？

**Comment by amingson** [comment]
> ![image](https://private-user-images.githubusercontent.com/626539/296523551-d2ed118b-6cea-46ec-8442-24315e970fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDgyMTgsIm5iZiI6MTcwNTIwNzkxOCwicGF0aCI6Ii82MjY1MzkvMjk2NTIzNTUxLWQyZWQxMThiLTZjZWEtNDZlYy04NDQyLTI0MzE1ZTk3MGZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwNDUxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODZkNGQ5Y2M3ZGMyYWUyZDI4YTM0YWM5MjcxMDNhN2M2MjljNmQ1ZWM1MjNkZGYxZWRiY2Y2NmI4MWViY2UzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kqS8FN53rkVeTvNjrP8G3Hg9fGfALiipKLGfHWKZy_0)
> 
> 是否有开通翻译服务？

Y叔您好，感谢您的回复。按照您的建议，我去开通这个服务，但是又遇到了一个问题，我的服务器主机是自己配的，用的研究所内部网络，没有公网IP，但是百度那边信息填写要求服务器ip地址，请问该如何解决?
![image](https://github.com/YuLab-SMU/fanyi/assets/102129816/7f5b81f1-a025-4443-b0cd-53ff064b3d05)


祝好！
Msong

**Comment by amingson** [comment]
> > ![image](https://private-user-images.githubusercontent.com/626539/296523551-d2ed118b-6cea-46ec-8442-24315e970fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMDgyMTgsIm5iZiI6MTcwNTIwNzkxOCwicGF0aCI6Ii82MjY1MzkvMjk2NTIzNTUxLWQyZWQxMThiLTZjZWEtNDZlYy04NDQyLTI0MzE1ZTk3MGZkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwNDUxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODZkNGQ5Y2M3ZGMyYWUyZDI4YTM0YWM5MjcxMDNhN2M2MjljNmQ1ZWM1MjNkZGYxZWRiY2Y2NmI4MWViY2UzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kqS8FN53rkVeTvNjrP8G3Hg9fGfALiipKLGfHWKZy_0)
> > 是否有开通翻译服务？
> 
> Y叔您好，感谢您的回复。按照您的建议，我去开通这个服务，但是又遇到了一个问题，我的服务器主机是自己配的，用的研究所内部网络，没有公网IP，但是百度那边信息填写要求服务器ip地址，请问该如何解决? ![image](https://private-user-images.githubusercontent.com/102129816/296533692-7f5b81f1-a025-4443-b0cd-53ff064b3d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTU1NzAsIm5iZiI6MTcwNTIxNTI3MCwicGF0aCI6Ii8xMDIxMjk4MTYvMjk2NTMzNjkyLTdmNWI4MWYxLWEwMjUtNDQ0My1iMGNkLTUzZmYwNjRiM2QwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwNjU0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTM2ZDMxNjhmM2UzZDU2ZjZiOWVkZWM0ZDQ2YWQ5ZTcwNTNkYTk5NDM3NDdkNjQ3Y2I0ODRkMTBmNzdlNGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.avwHn3BYXocDpYIDBlA698lDxBZquPOYdZFTN2hJATY)
> 
> 祝好！ Msong

已经调试成功，这里的ip地址不需要填写。再次感谢Y叔的帮助！！！
