### ISSUE TITLE
character(0)

### ISSUE THREAD

**Issue by fengxueyu** [YuLab-SMU/fanyi#25]
character(0)

**Comment by Tinalxt** [comment]
I got the same ouput by using translate()
![image](https://github.com/user-attachments/assets/deee26df-b15b-4e8e-8cca-3968ee59bebe)

**Comment by GuangchuangYu** [comment]
![image](https://github.com/user-attachments/assets/546904e3-2314-4e7b-99aa-1ad228517b81)

**Comment by Xiaoxi-Hu** [comment]
Me too
<img width="594" alt="截屏2024-07-22 00 12 21" src="https://github.com/user-attachments/assets/dcfc8109-e706-4510-aabd-4d892dc457dc">

**Comment by qianzhao613** [comment]
另一个问题中有类似的情况<https://github.com/YuLab-SMU/fanyi/issues/21>，可能是由于没有开通“通用文本翻译”。我刚才试了一下，没有开通就会返回character(0)，开通之后就正常了。
