### ISSUE TITLE
腾讯机器翻译错误

### ISSUE THREAD

**Issue by xleizi** [YuLab-SMU/fanyi#30]
Y叔您好，我在您的readme文件中看到tencent翻译需要填入的是secrets值，但是set_translate_option()函数中无法填入secrets值，并且填入key值之后，无法进行翻译
to use tencent (腾讯机器翻译) translate:
go to https://console.cloud.tencent.com/ and register;
login with your account, go to https://console.cloud.tencent.com/tmt to enable machine translation (启用机器翻译);
go to https://console.cloud.tencent.com/cam/user/userType, create a sub-account, in Permissions (权限) - Permissions policy (权限策略), search and add QcloudTMTReadOnlyAccess;
get your API keys at API keys (API 密钥) of the same page in step 3. set SecretId as the appid and SecretKey as secrets respectively with source = "tencent" using set_translate_option()
have fun with tencent_translate()
for supported languages, visit https://cloud.tencent.com/document/product/551/15611 for more information.

**Comment by GuangchuangYu** [comment]
![image](https://github.com/YuLab-SMU/fanyi/assets/626539/0f40427b-7d72-419a-8418-7f3486b26804)

你没搞对吧。亲测可用。

**Comment by xleizi** [comment]
谢谢Y叔，我找到原因了，我专门测试了一下api试了一下，设置账号的时候只用QcloudTMTReadOnlyAccess无法请求成功，需要添加上QcloudTMTFullAccess
