### ISSUE TITLE
chatglm不能正确工作

### ISSUE THREAD

**Issue by bionoob7** [YuLab-SMU/fanyi#31]
Y叔您好，在 `https://open.bigmodel.cn/usercenter/apikeys` 申请完key,实名认证也填了，但是当我运行以下代码时，总会报错
```
library(fanyi)
set_translate_option(source = "chatglm",
                     key = "xxxxxxxxxxxxxxxxxxxxx",
                     appid = "",
                     user_model = "glm-4")

chatglm_translate('you are a good')
```
Error in parser$events : $ operator is invalid for atomic vectors
请问您，我已经如何解决，谢谢！

**Comment by GuangchuangYu** [comment]
same here, <https://github.com/YuLab-SMU/fanyi/pull/27#issuecomment-1977829536>

@MitsuhaMiyamizu please check.

**Comment by MitsuhaMiyamizu** [comment]
Fixed, please see #32 .

**Comment by bionoob7** [comment]
well done,thanks!
