### ISSUE TITLE
Consider: migrate httr to httr2 due to lack of maintenance of the former package.

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [YuLab-SMU/fanyi#7]
According to https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html,

>httr is no longer recommended for new code: we recommend [httr2](https://httr2.r-lib.org/).

Sometimes it's hard to find documentation of httr, it might be better to refrain from using the obsolete package (httr).

**Comment by GuangchuangYu** [comment]
that's a neat idea.

**Comment by MitsuhaMiyamizu** [comment]
#12 #11 Resolved, issue will be closed now.
